name: Deploy to Kuzzle PaaS
description: Deploy a new version of an application to Kuzzle PaaS

inputs:
  username:
    description: Kuzzle PaaS username
    required: true
  password:
    description: Kuzzle PaaS password
    required: true
  application:
    description: The application name to deploy
    required: true
  environment:
    description: The environment to deploy to
    required: true
  docker_registry:
    description: The Docker registry to use to push the application
    required: false
    default: harbor.paas.kuzzle.io
  tag:
    description: The Docker image tag to deploy (the current commit SHA will be used if not provided)
    required: false

runs:
  using: "composite"
  steps:
    - name: Using a helper to compute default image tag using the current commit SHA
      id: vars
      shell: bash
      run: |
        export DEFAULT_TAG=$(git rev-parse --short HEAD)
        export PROVIDED_TAG=${{ inputs.tag }}
        echo "::set-output name=tag::${PROVIDED_TAG:-$DEFAULT_TAG}"
        echo "::set-output name=project::$(jq -r .kuzzle.paas.project package.json)"
    - name: Login to Kuzzle PaaS using Kourou CLI
      shell: bash
      env:
        KUZZLE_PAAS_USERNAME: ${{ inputs.username }}
        KUZZLE_PAAS_PASSWORD: ${{ inputs.password }}
      run: |
        set -e
        npx kourou paas:login --project ${{ steps.vars.outputs.project }} --username ${{ inputs.username }}
        echo "Login successful..."
    - name: Login and deploy to Kuzzle PaaS using Kourou CLI
      shell: bash
      run: |
        set -e
        echo "Updating ${{ inputs.application }} application of ${{ inputs.environment }} environment using image ${{ inputs.image }}:${{ steps.vars.outputs.tag }} ..."
        npx kourou paas:deploy --project ${{ steps.vars.outputs.project }} ${{ inputs.environment }} ${{ inputs.application }} ${{ inputs.docker_registry }}/${{ steps.vars.outputs.project }}/${{ inputs.environment }}/${{ inputs.application }}:${{ steps.vars.outputs.tag }}
