name: "Danger JS"
on:
  workflow_call:
    inputs:
      rules:
        description: 'List of branches allowed to be merge in the current branch'
        required: true
        type: string

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Danger
      uses: danger/danger-js@9.1.6
      with:
        args: "--dangerfile branch-merge-check.ts"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RULES: ${{ inputs.rules }}