name: "Danger JS"
on:
  workflow_call:
    inputs:
      DANGER_CONFIG:
        description: 'Danger configuration file'
        required: true
        type: string

jobs:
  danger-js:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Danger
      uses: danger/danger-js@9.1.6
      with:
        args: "--dangerfile danger.ts"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DANGER_CONFIG: ${{ inputs.DANGER_CONFIG }}