name: "Danger JS"
on:
  workflow_call:
    inputs:
      DANGER_CONFIG:
        description: 'Danger configuration file'
        required: true
        type: string

jobs:
  danger-js:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: main
    - uses: actions/checkout@v3
      with:
        repository: kuzzleio/ci-tooling
        path: ci-tooling
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Build Danger Checks
      working-directory: ci-tooling
      env:
        NODE_ENV: development
      run: |
        npm i
        npm run build
    - name: Run Danger Checks
      working-directory: main
      run: |
        npx danger ci --dangerfile $GITHUB_WORKSPACE/ci-tooling/danger.js
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DANGER_CONFIG: ${{ inputs.DANGER_CONFIG }}
      SOURCE_FOLDER: main