name: Documentation Deploy
on:
  workflow_call:

doc-deploy:
  name: Documentation - Deploy
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Extract references from context
      shell: bash
      id: extract-refs
      run: |
        echo "::set-output name=version::$(git describe --abbrev=0 --tags | cut -d. -f 1)"
        echo "::set-output name=repo::$(echo $GITHUB_REPOSITORY | cut -d/ -f 2)"
        echo "::set-output name=branch::$(echo $GITHUB_REF | cut -d/ -f 3)"
    - uses: convictional/trigger-workflow-and-wait@v1.6.3
      with:
        owner: kuzzleio
        repo: documentation
        github_token: ${{ secrets.ACCESS_TOKEN_CI }}
        workflow_file_name: child_repo.workflow.yml
        ref: ${{ github.ref_name == 'master' && 'master' || 'develop' }}
        client_payload: '{"repo_name":"${{ steps.extract-refs.outputs.repo }}","branch":"${{ steps.extract-refs.outputs.branch }}","version":"${{ steps.extract-refs.outputs.version }}"}'