name: NPM Deploy
on:
  workflow_call:
    inputs:
      build:
        description: 'Danger configuration file'
        default: false
        required: false
        type: boolean


jobs:
  npm-deploy:
    name: Build and deploy release on NPM.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_LTS_ACTIVE_VERSION }}
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run build
        if: ${{ inputs.build }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
