name: Build and Publish To Github
on:
  workflow_call:
    inputs:
      build:
        description: 'Build the package before publishing it'
        default: false
        required: false
        type: boolean
  
jobs:
  publish-github-package:
    name: Deploy package to the Github NPM registry
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Set Github package registry
        run: npm config set @kuzzleio:registry https://npm.pkg.github.com
      - name: Github package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GPR_TOKEN }}
      - run: npm install
      - run: npm run build
        if: ${{ inputs.build }}
      - run: npm publish
