name: "Danger JS"
on: [pull_request]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Danger
      uses: danger/danger-js@9.1.6
      with:
        args: "--dangerfile dangerfile.ts"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}