name: "Danger JS"
on: [pull_request]

jobs:
  check-branch:
    name: Check Pull Request Branch
    uses: kuzzleio/ci-tooling/tree/branch-check/shared/workflows/branch_check.yaml
    secrets: inherit
    with:
      rules: '{"master":["2-dev"]}'